spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=${spring.datasource.driver-class-name}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=${spring.jpa.open-in-view}

spring.servlet.multipart.max-file-size=${spring.servlet.multipart.max-file-size}

jwt.secret=${jwt.secret}
